name: snowflake_schemachange

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'dev_scripts/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: '3.8.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install schemachange

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SNW_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SNW_USER }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_DATABASE: ${{ secrets.SNW_DATABASE }}
          SF_WAREHOUSE: ${{ secrets.SNW_WAREHOUSE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNW_PASSWORD }}  # Pass the Snowflake password as an environment variable
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Python Version:"
          python --version
          echo "Installing schemachange..."
          echo "Running schemachange..."
          schemachange -f $GITHUB_WORKSPACE/dev_scripts -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
